<a href="https://colab.research.google.com/github/Ameer24-03/Ameer24-03/blob/main/House_Pricing_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [4]:
data =pd.read_csv('/content/train.csv')

NameError: name 'pd' is not defined

In [ ]:
data.head()

   beds  baths  size size_units  lot_size lot_size_units  zip_code    price
0     3    2.5  2590       sqft   6000.00           sqft     98144   795000
1     4    2.0  2240       sqft      0.31           acre     98106   915000
2     4    3.0  2040       sqft   3783.00           sqft     98107   950000
3     4    3.0  3800       sqft   5175.00           sqft     98199  1950000
4     2    2.0  1042       sqft       NaN            NaN     98102   950000

from matplotlib import pyplot as plt
_df_0['beds'].plot(kind='hist', bins=20, title='beds')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['baths'].plot(kind='hist', bins=20, title='baths')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['size'].plot(kind='hist', bins=20, title='size')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['lot_size'].plot(kind='hist', bins=20, title='lot_size')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('lot_size_units').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='beds', y='baths', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='baths', y='size', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='size', y='lot_size', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8.plot(kind='scatter', x='lot_size', y='zip_code', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_9['beds'].plot(kind='line', figsize=(8, 4), title='beds')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['baths'].plot(kind='line', figsize=(8, 4), title='baths')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_11['size'].plot(kind='line', figsize=(8, 4), title='size')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_12['lot_size'].plot(kind='line', figsize=(8, 4), title='lot_size')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_13['lot_size_units'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_13, x='beds', y='lot_size_units', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_14['lot_size_units'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_14, x='baths', y='lot_size_units', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_15['lot_size_units'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_15, x='size', y='lot_size_units', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_16['lot_size_units'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_16, x='lot_size', y='lot_size_units', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
data.shape

(2016, 8)

In [ ]:
data.info

<bound method DataFrame.info of       beds  baths  size size_units  lot_size lot_size_units  zip_code    price
0        3    2.5  2590       sqft   6000.00           sqft     98144   795000
1        4    2.0  2240       sqft      0.31           acre     98106   915000
2        4    3.0  2040       sqft   3783.00           sqft     98107   950000
3        4    3.0  3800       sqft   5175.00           sqft     98199  1950000
4        2    2.0  1042       sqft       NaN            NaN     98102   950000
...    ...    ...   ...        ...       ...            ...       ...      ...
2011     3    2.0  1370       sqft      0.50           acre     98112   910000
2012     1    1.0   889       sqft       NaN            NaN     98121   550000
2013     4    2.0  2140       sqft   6250.00           sqft     98199  1150000
2014     2    2.0   795       sqft       NaN            NaN     98103   590000
2015     3    2.0  1710       sqft   4267.00           sqft     98133   659000

[2016 rows x 8 columns]>

In [ ]:
for coloumn in data.columns:
  print(data[coloumn].value_counts)
  print('*'*20)

<bound method IndexOpsMixin.value_counts of 0       3
1       4
2       4
3       4
4       2
       ..
2011    3
2012    1
2013    4
2014    2
2015    3
Name: beds, Length: 2016, dtype: int64>
********************
<bound method IndexOpsMixin.value_counts of 0       2.5
1       2.0
2       3.0
3       3.0
4       2.0
       ...
2011    2.0
2012    1.0
2013    2.0
2014    2.0
2015    2.0
Name: baths, Length: 2016, dtype: float64>
********************
<bound method IndexOpsMixin.value_counts of 0       2590
1       2240
2       2040
3       3800
4       1042
        ...
2011    1370
2012     889
2013    2140
2014     795
2015    1710
Name: size, Length: 2016, dtype: int64>
********************
<bound method IndexOpsMixin.value_counts of 0       sqft
1       sqft
2       sqft
3       sqft
4       sqft
        ...
2011    sqft
2012    sqft
2013    sqft
2014    sqft
2015    sqft
Name: size_units, Length: 2016, dtype: object>
********************
<bound method IndexOpsMixin.value_counts of 0       6000.00
1          0.31
2       3783.00
3       5175.00
4           NaN
         ...
2011       0.50
2012        NaN
2013    6250.00
2014        NaN
2015    4267.00
Name: lot_size, Length: 2016, dtype: float64>
********************
<bound method IndexOpsMixin.value_counts of 0       sqft
1       acre
2       sqft
3       sqft
4        NaN
        ...
2011    acre
2012     NaN
2013    sqft
2014     NaN
2015    sqft
Name: lot_size_units, Length: 2016, dtype: object>
********************
<bound method IndexOpsMixin.value_counts of 0       98144
1       98106
2       98107
3       98199
4       98102
        ...
2011    98112
2012    98121
2013    98199
2014    98103
2015    98133
Name: zip_code, Length: 2016, dtype: int64>
********************
<bound method IndexOpsMixin.value_counts of 0        795000
1        915000
2        950000
3       1950000
4        950000
         ...
2011     910000
2012     550000
2013    1150000
2014     590000
2015     659000
Name: price, Length: 2016, dtype: int64>
********************

In [ ]:
data.isna().sum()

beds                0
baths               0
size                0
size_units          0
lot_size          347
lot_size_units    347
zip_code            0
price               0
dtype: int64

In [ ]:
data.drop(columns=['lot_size','lot_size_units'],inplace=True)

In [ ]:
data.describe()

              beds        baths          size      zip_code         price
count  2016.000000  2016.000000   2016.000000   2016.000000  2.016000e+03
mean      2.857639     2.159970   1735.740575  98123.638889  9.636252e+05
std       1.255092     1.002023    920.132591     22.650819  9.440954e+05
min       1.000000     0.500000    250.000000  98101.000000  1.590000e+05
25%       2.000000     1.500000   1068.750000  98108.000000  6.017500e+05
50%       3.000000     2.000000   1560.000000  98117.000000  8.000000e+05
75%       4.000000     2.500000   2222.500000  98126.000000  1.105250e+06
max      15.000000     9.000000  11010.000000  98199.000000  2.500000e+07

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2016 entries, 0 to 2015
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   beds        2016 non-null   int64
 1   baths       2016 non-null   float64
 2   size        2016 non-null   float64
 3   size_units  2016 non-null   object
 4   zip_code    2016 non-null   int64
 5   price       2016 non-null   float64
dtypes: float64(3), int64(2), object(1)
memory usage: 94.6+ KB

In [ ]:
data['beds'].value_counts()

beds
3     645
2     560
4     398
1     256
5     123
6      22
9       5
7       3
8       2
15      1
14      1
Name: count, dtype: int64

In [ ]:
data.head()

   beds  baths    size size_units  zip_code      price
0     3    2.5  2590.0       sqft     98144   795000.0
1     4    2.0  2240.0       sqft     98106   915000.0
2     4    3.0  2040.0       sqft     98107   950000.0
3     4    3.0  3800.0       sqft     98199  1950000.0
4     2    2.0  1042.0       sqft     98102   950000.0

# **Price Per Suare feet**

In [ ]:
data['price_per_sqft']=data['price']*100000/data['size']

In [ ]:
data['price_per_sqft']

0       3.069498e+07
1       4.084821e+07
2       4.656863e+07
3       5.131579e+07
4       9.117083e+07
            ...
2011    6.642336e+07
2012    6.186727e+07
2013    5.373832e+07
2014    7.421384e+07
2015    3.853801e+07
Name: price_per_sqft, Length: 2016, dtype: float64

In [ ]:
data.describe()

,beds,baths,size,zip_code,price,price_per_sqft
count,2016.000000,2016.000000,2016.000000,2016.000000,2.016000e+03,2.016000e+03
mean,2.857639,2.159970,1735.740575,98123.638889,9.636252e+05,5.915851e+07
std,1.255092,1.002023,920.132591,22.650819,9.440954e+05,8.327952e+07
min,1.000000,0.500000,250.000000,98101.000000,1.590000e+05,6.796117e+06
25%,2.000000,1.500000,1068.750000,98108.000000,6.017500e+05,4.452221e+07
50%,3.000000,2.000000,1560.000000,98117.000000,8.000000e+05,5.529762e+07
75%,4.000000,2.500000,2222.500000,98126.000000,1.105250e+06,6.595389e+07
max,15.000000,9.000000,11010.000000,98199.000000,2.500000e+07,3.424658e+09

In [ ]:
data.shape

(2016, 7)

In [ ]:
data

      beds  baths    size size_units  zip_code      price  price_per_sqft
0        3    2.5  2590.0       sqft     98144   795000.0    3.069498e+07
1        4    2.0  2240.0       sqft     98106   915000.0    4.084821e+07
2        4    3.0  2040.0       sqft     98107   950000.0    4.656863e+07
3        4    3.0  3800.0       sqft     98199  1950000.0    5.131579e+07
4        2    2.0  1042.0       sqft     98102   950000.0    9.117083e+07
...    ...    ...     ...        ...       ...        ...             ...
2011     3    2.0  1370.0       sqft     98112   910000.0    6.642336e+07
2012     1    1.0   889.0       sqft     98121   550000.0    6.186727e+07
2013     4    2.0  2140.0       sqft     98199  1150000.0    5.373832e+07
2014     2    2.0   795.0       sqft     98103   590000.0    7.421384e+07
2015     3    2.0  1710.0       sqft     98133   659000.0    3.853801e+07

[2016 rows x 7 columns]

In [ ]:
data.drop(columns=['size_units'],inplace=True)

In [ ]:
data.drop(columns=['price_per_sqft'],inplace=True)

In [ ]:
data.head()

   beds  baths    size  zip_code      price
0     3    2.5  2590.0     98144   795000.0
1     4    2.0  2240.0     98106   915000.0
2     4    3.0  2040.0     98107   950000.0
3     4    3.0  3800.0     98199  1950000.0
4     2    2.0  1042.0     98102   950000.0

In [ ]:
data.to_csv("/content/final_dataset.csv")

In [ ]:
X=data.drop(columns=['price'])
y=data['price']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=0)

In [ ]:
print(X_train.shape)
print(y_train.shape)

(1612, 4)
(1612,)

# **Applying Linear Regression**

In [ ]:
column_trans = make_column_transformer((OneHotEncoder(sparse_output=False),['beds']),remainder='passthrough')

In [ ]:
scaler = StandardScaler()

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
lr = LinearRegression()
lr.fit(X_scaled, y)

LinearRegression()

In [ ]:
pipe = make_pipeline(column_trans,scaler,lr)

In [ ]:
pipe.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/compose/_column_transformer.py:1651: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['beds'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [ ]:
y_pred_lr=pipe.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
score = r2_score(y_test, y_pred_lr)
print(score)

0.5746816285348347

# **Using Lasso**

In [ ]:
lasso = Lasso()

In [ ]:
pipe = make_pipeline(column_trans,scaler,lasso)

In [ ]:
pipe.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/compose/_column_transformer.py:1651: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['beds'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [ ]:
y_pred_lasso = pipe.predict(X_test)
r2_score(y_test,y_pred_lasso)

0.5746817917322382

# **Using Ridge**

In [ ]:
ridge = Ridge()

In [ ]:
pipe = make_pipeline(column_trans,scaler,ridge)

In [ ]:
pipe.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/compose/_column_transformer.py:1651: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['beds'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [ ]:
y_pred_ridge = pipe.predict(X_test)
r2_score(y_test,y_pred_ridge)

0.5746884627878556

In [ ]:
print("No Regularization:",r2_score(y_test,y_pred_lr))
print('Lasso',r2_score(y_test,y_pred_lasso))
print('Ridge',r2_score(y_test,y_pred_ridge))

No Regularization: 0.5746816285348347
Lasso 0.5746817917322382
Ridge 0.5746884627878556

In [ ]:
import pickle

In [ ]:
pickle.dump(pipe,open('RidgeModel.pkl','wb'))

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
import joblib
def load_data(csv_file):
    data = pd.read_csv('/content/final_dataset.csv')
    return data
def preprocess_data(data):
    X = data[['beds', 'baths', 'size', 'zip_code']]
    y = data['price']
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    return X_scaled, y, scaler
def train_model(X, y):
    model = LinearRegression()
    model.fit(X, y)
    return model
def predict_price(model, scaler, beds, baths, size, zip_code):
    input_data = [[beds, baths, size, zip_code]]
    input_data_scaled = scaler.transform(input_data)
    prediction = model.predict(input_data_scaled)
    return prediction[0]
def save_model(model, scaler, model_file, scaler_file):
    joblib.dump(model, model_file)
    joblib.dump(scaler, scaler_file)
def load_model(model_file, scaler_file):
    model = joblib.load(model_file)
    scaler = joblib.load(scaler_file)
    return model, scaler
def main():
    data = load_data('/content/final_dataset.csv')
    X, y, scaler = preprocess_data(data)
    model = train_model(X, y)
    save_model(model, scaler, 'house_price_model.pkl', 'scaler.pkl')
    beds = int(input("Enter number of bedrooms: "))
    baths = int(input("Enter number of bathrooms: "))
    size = float(input("Enter size of the house in sqft: "))
    zip_code = int(input("Enter zip code: "))
    predicted_price = predict_price(model, scaler, beds, baths, size, zip_code)
    print(f"Predicted House Price: ${predicted_price:,.2f}")
if __name__ == "__main__":
    main()

FileNotFoundError: [Errno 2] No such file or directory: '/content/final_dataset.csv'